name: feelings
description: A new Flutter project with Hive + Bloc + GetIt
publish_to: "none"

environment:
  sdk: "3.10.1"

dependencies:
  flutter:
    sdk: flutter

  # --- Hive database ---
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # --- Hive generator ---
  path_provider: ^2.1.2

  # --- State management ---
  bloc: ^8.1.2
  flutter_bloc: ^8.1.2

  # --- Dependency Injection ---
  get_it: ^7.6.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.7
  hive_generator: ^2.0.1
